# Site settings
title: Li Qingyao
email: qingyao.li@yahoo.com
description: Hello World
baseurl: ""
url: "http://code.liqingyao.com"

author:
  name     : 'Li Qingyao'
  email    : qingyao.li@yahoo.com
  url      : http://code.liqingyao.com
  facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/liqingyao
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
